default: &default
  adapter:  postgresql
  encoding: unicode
  encoding: utf8
  port:     <%= ENV.fetch('DB_PORT', '5432') %>
  pool:     <%= ENV.fetch('DB_MAX_THREADS', 5) %>
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV.fetch('DB_DATABASE') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>

test:
  <<: *default

development:
  <<: *default

deploy_dev:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
