default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_frontend: <%= ENV["DOMAIN_FRONTEND"] %>
  domain_backend: <%= ENV["DOMAIN_BACKEND"] %>
  default_from_email: <%= ENV["DEFAULT_FROM_EMAIL"] %>

  s3:
    aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
    aws_secret_access_key: <%= ENV["AWS_SECRET"] %>
    aws_region: <%= ENV["AWS_REGION"]%>
    aws_bucket: <%= ENV["AWS_BUCKET"] %>

  sendgrid:
    username: <%= ENV["SENDGRID_USERNAME"] %>
    password: <%= ENV["SENDGRID_PASSWORD"] %>
development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
